### PR TITLE
Separate dev and prod setups. Isolate services in dedicated containers

### PR DESCRIPTION
**Pull request by ArturMoczulski**
https://github.com/delconis/atavism-server-docker/issues/1

This separates the docker setup into development and production.

development maps the local server files to the containers so images do not have to be rebuilt on updating server files.

production works mostly as before by copying server files from host to container.

Introduces `ATAVISM_ALL_IN_ONE_ENABLED:false` in the `.env` files to easily switch between separate processes and all_in_one. Defaults to separate processes to provide separated log files.

Note this removes support for .zip server files and assumes you have unzipped Atavism Server copy.

It also removes custom Dockerfile for MySQL as unzipping server files is not necessary anymore.

### CODE REVIEW

**Comment by delconis** [comment]
I'm having a issue running it saying the `env.sh` is not found causing all but the SQL servers to fail starting.

I think it might be since the files are not `chmod +x` since they are copied over via compose from what gets packaged in the image.

Both development and production variants produced this. 

```
: not foundver-development-master-1         | start.sh: 1:
: not foundver-development-master-1         | start.sh: 7:
: No such file-development-master-1         | start.sh: 8: .: cannot open /env.sh
: not foundver-development-world-1          | start.sh: 1:
: not foundver-development-world-1          | start.sh: 7:
: No such file-development-world-1          | start.sh: 8: .: cannot open /env.sh
```

**Comment by ArturMoczulski** [comment]
I have a massive update coming including auto generation of plug-in registrations on grade  build.

Could be best to wait until that's finished before merging the fork

**Comment by ArturMoczulski** [comment]
I'm working on do all the plugin and client messages registration happen automatically on gradle build which in turn happens automatically on VS code file save.

I have a big part of it. I'm just finishing up all the places where code autogeneration needs to happen

**Comment by ArturMoczulski** [comment]
I'll drop this PR in favor of a new one once complete

**Pull request closed without merging**
